### ISSUE TITLE
Error Since Upgrade to Python 3.11

### ISSUE THREAD

**Issue by LinuxAndCoffee** [NayamAmarshe/please#48]
When I open my terminal after upgrading to Python 3.11 I get the following errors:

Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/please", line 33, in <module>
    sys.exit(load_entry_point('please-cli==0.3.1', 'console_scripts', 'please')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/please", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for please-cli

Please let me know if I can provide any additional information to help with this. And thank you for building Please, it always brings a smile to my face when I launch my terminal. :)

**Comment by NayamAmarshe** [comment]
It seems that Python 3.11 is not supported.
Would it be possible for you to install Python 3.10?

python3.10 -m pip install please-cli

**Comment by LinuxAndCoffee** [comment]
Silly question: can I have both Python 3.11 and Python 3.10 installed at the same time?

**Comment by NayamAmarshe** [comment]
> Silly question: can I have both Python 3.11 and Python 3.10 installed at the same time?

Yes of course!
